# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventoPrincipal', models.CharField(max_length=128)),
                ('nome', models.CharField(max_length=128)),
                ('data_inicio', models.DateTimeField()),
                ('logotipo', models.CharField(max_length=128)),
                ('palavrasChave', models.CharField(max_length=128)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('endereco', models.CharField(max_length=250)),
                ('cep', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=258)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento_cientifico.Pessoa')),
                ('curriculo', models.CharField(max_length=128)),
                ('artigos', models.CharField(max_length=128, null=True)),
                ('pai', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
            bases=('evento_cientifico.pessoa',),
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento_cientifico.Evento')),
                ('issn', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'Evento Cientifico',
                'verbose_name_plural': 'Eventos Cientificos',
            },
            bases=('evento_cientifico.evento',),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento_cientifico.Pessoa')),
                ('cpf', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'Pessoa Fisica',
                'verbose_name_plural': 'Pessoas Fisicas',
            },
            bases=('evento_cientifico.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento_cientifico.Pessoa')),
                ('cnpj', models.CharField(max_length=14)),
                ('razaoSocial', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Pessoa Juridica',
                'verbose_name_plural': 'Pessoas Juridica',
            },
            bases=('evento_cientifico.pessoa',),
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realizadores', to='evento_cientifico.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='evento_cientifico.EventoCientifico'),
        ),
    ]
