# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento_cientifico', '0003_auto_20170911_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='artigos',
        ),
    ]
