# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento_cientifico', '0004_remove_autor_artigos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='pai',
        ),
    ]
