# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento_cientifico', '0005_remove_autor_pai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realizadores', to='evento_cientifico.Pessoa'),
        ),
    ]
